/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellUploadImagesRouteImport } from './routes/sell.upload-images'
import { Route as SellUploadDocsRouteImport } from './routes/sell.upload-docs'
import { Route as SellSetPriceRouteImport } from './routes/sell.set-price'
import { Route as SellNewRouteImport } from './routes/sell.new'
import { Route as SellDetailsRouteImport } from './routes/sell.details'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellUploadImagesRoute = SellUploadImagesRouteImport.update({
  id: '/sell/upload-images',
  path: '/sell/upload-images',
  getParentRoute: () => rootRouteImport,
} as any)
const SellUploadDocsRoute = SellUploadDocsRouteImport.update({
  id: '/sell/upload-docs',
  path: '/sell/upload-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SellSetPriceRoute = SellSetPriceRouteImport.update({
  id: '/sell/set-price',
  path: '/sell/set-price',
  getParentRoute: () => rootRouteImport,
} as any)
const SellNewRoute = SellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SellDetailsRoute = SellDetailsRouteImport.update({
  id: '/sell/details',
  path: '/sell/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/sell/details': typeof SellDetailsRoute
  '/sell/new': typeof SellNewRoute
  '/sell/set-price': typeof SellSetPriceRoute
  '/sell/upload-docs': typeof SellUploadDocsRoute
  '/sell/upload-images': typeof SellUploadImagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/sell/details': typeof SellDetailsRoute
  '/sell/new': typeof SellNewRoute
  '/sell/set-price': typeof SellSetPriceRoute
  '/sell/upload-docs': typeof SellUploadDocsRoute
  '/sell/upload-images': typeof SellUploadImagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/sell/details': typeof SellDetailsRoute
  '/sell/new': typeof SellNewRoute
  '/sell/set-price': typeof SellSetPriceRoute
  '/sell/upload-docs': typeof SellUploadDocsRoute
  '/sell/upload-images': typeof SellUploadImagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/my-listings'
    | '/notifications'
    | '/register'
    | '/chat/$conversationId'
    | '/listing/$id'
    | '/sell/details'
    | '/sell/new'
    | '/sell/set-price'
    | '/sell/upload-docs'
    | '/sell/upload-images'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/my-listings'
    | '/notifications'
    | '/register'
    | '/chat/$conversationId'
    | '/listing/$id'
    | '/sell/details'
    | '/sell/new'
    | '/sell/set-price'
    | '/sell/upload-docs'
    | '/sell/upload-images'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/my-listings'
    | '/notifications'
    | '/register'
    | '/chat/$conversationId'
    | '/listing/$id'
    | '/sell/details'
    | '/sell/new'
    | '/sell/set-price'
    | '/sell/upload-docs'
    | '/sell/upload-images'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyListingsRoute: typeof MyListingsRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ListingIdRoute: typeof ListingIdRoute
  SellDetailsRoute: typeof SellDetailsRoute
  SellNewRoute: typeof SellNewRoute
  SellSetPriceRoute: typeof SellSetPriceRoute
  SellUploadDocsRoute: typeof SellUploadDocsRoute
  SellUploadImagesRoute: typeof SellUploadImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/upload-images': {
      id: '/sell/upload-images'
      path: '/sell/upload-images'
      fullPath: '/sell/upload-images'
      preLoaderRoute: typeof SellUploadImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/upload-docs': {
      id: '/sell/upload-docs'
      path: '/sell/upload-docs'
      fullPath: '/sell/upload-docs'
      preLoaderRoute: typeof SellUploadDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/set-price': {
      id: '/sell/set-price'
      path: '/sell/set-price'
      fullPath: '/sell/set-price'
      preLoaderRoute: typeof SellSetPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/new': {
      id: '/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof SellNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/details': {
      id: '/sell/details'
      path: '/sell/details'
      fullPath: '/sell/details'
      preLoaderRoute: typeof SellDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyListingsRoute: MyListingsRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  ListingIdRoute: ListingIdRoute,
  SellDetailsRoute: SellDetailsRoute,
  SellNewRoute: SellNewRoute,
  SellSetPriceRoute: SellSetPriceRoute,
  SellUploadDocsRoute: SellUploadDocsRoute,
  SellUploadImagesRoute: SellUploadImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
